---
# tasks file for docker-machine
- name: Install required packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Get the current operating system name.
  command: uname -s
  changed_when: false
  register: operation_system_name

- name: Get the current machine hardware name.
  command: uname -m
  changed_when: false
  register: hardware_name

- name: Install docker-machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-{{ operation_system_name.stdout }}-{{ hardware_name.stdout }}
    dest: /usr/local/bin/docker-machine
    mode: 755
