gitlab_runner_token = "kAcoXExMjq-X7t1KJTdy"
key_name            = "bsasam"
environment         = "tests"
vpc_id              = "vpc-3c6e8c41"
private_subnet_name = "default-pub-1"
public_subnet_name  = "default-pri-1"
GITLAB_RUNNER_NAME  = "gitlab-runner-1"